### PR TITLE
Add Japanese Translation and remove old Japanese translations

### PR DESCRIPTION
**Pull request by Apricot-ale**
Translation of campaigns and locations.
Others are WIP.

It also contains updates to mod.cpp / config.cpp. (Added my name to the author)

### CODE REVIEW

**Comment by Apricot-ale** [comment]
One more update soon, please wait.

**Comment by Apricot-ale** [comment]
updated
cleared to merge

**Comment by mihuan-0** [comment]
Please check line 29992

**Comment by Apricot-ale** [comment]
Oops, ok. I'll fix that.

**Comment by Apricot-ale** [comment]
ready to merge!

**Comment by Apricot-ale** [comment]
This update will add Campaign Translation. 
30% Complate

**Pull request merged**
